import { Carousel } from "./carousel";
import { EventCard } from "./event-card";
import Link from "next/link";
export const events = [
  {
    eventName: "Arijit Singh Live in Concert",
    image: "https://picsum.photos/id/242/1920/1080",
    date: "2024-03-18",
    time: "19:00",
    venue: "DY Patil Stadium",
    location: "Mumbai, MH",
    section: "Silver",
    seat: "B15",
    ticketHolder: "Available",
    bookingRef: "BMS-AS-001",
    eventType: "Concert",
    ageRating: "all",
    reviews: 4.8,
    ticketPrice: 1000,
    ticketQuantity: 100,
  },
  {
    eventName: "Zakir Hussein - Masters of Percussion",
    image: "https://picsum.photos/id/241/1920/1080",
    date: "2024-03-22",
    time: "18:30",
    venue: "Shanmukhananda Hall",
    location: "Mumbai, MH",
    section: "Premium",
    seat: "A12",
    ticketHolder: "Available",
    bookingRef: "BMS-ZH-002",
    eventType: "Classical",
    ageRating: "all",
    reviews: 4.9,
    ticketPrice: 1000,
    ticketQuantity: 100,
  },
  {
    eventName: "IPL: MI vs CSK",
    image: "https://picsum.photos/id/240/1920/1080",
    date: "2024-03-25",
    time: "19:30",
    venue: "Wankhede Stadium",
    location: "Mumbai, MH",
    section: "East Stand",
    seat: "E45",
    ticketHolder: "Available",
    bookingRef: "BMS-IPL-003",
    eventType: "Sports",
    ageRating: "all",
    reviews: 4.5,
    ticketPrice: 1000,
    ticketQuantity: 100,
  },
  {
    eventName: "Vir Das - Mind Fool Tour",
    image: "https://picsum.photos/id/239/1920/1080",
    date: "2024-03-28",
    time: "20:00",
    venue: "Mehboob Studio",
    location: "Mumbai, MH",
    section: "VIP",
    seat: "C21",
    ticketHolder: "Available",
    bookingRef: "BMS-VD-004",
    eventType: "Stand-up Comedy",
    ageRating: "mature",
    reviews: 4.3,
    ticketPrice: 1000,
    ticketQuantity: 100,
  },
  {
    eventName: "Sunburn Arena ft. Martin Garrix",
    image: "https://picsum.photos/id/238/1920/1080",
    date: "2024-04-01",
    time: "16:00",
    venue: "Mahalaxmi Race Course",
    location: "Mumbai, MH",
    section: "GA",
    seat: "N/A",
    ticketHolder: "Available",
    bookingRef: "BMS-SB-005",
    eventType: "EDM",
    ageRating: "teen",
    reviews: 4.4,
    ticketPrice: 1000,
    ticketQuantity: 100,
  },
  {
    eventName: "Mughal-e-Azam: The Musical",
    image: "https://picsum.photos/id/237/1920/1080",
    date: "2024-04-05",
    time: "19:00",
    venue: "NCPA",
    location: "Mumbai, MH",
    section: "Royal Circle",
    seat: "D12",
    ticketHolder: "Available",
    bookingRef: "BMS-MA-006",
    eventType: "Theatre",
    ageRating: "all",
    reviews: 4.7,
    ticketPrice: 1000,
    ticketQuantity: 100,
  },
  {
    eventName: "Divine - Desi Hip Hop Night",
    image: "https://picsum.photos/id/24/1920/1080",
    date: "2024-04-08",
    time: "21:00",
    venue: "Antisocial",
    location: "Mumbai, MH",
    section: "Standing",
    seat: "N/A",
    ticketHolder: "Available",
    bookingRef: "BMS-DV-007",
    eventType: "Concert",
    ageRating: "teen",
    reviews: 4.2,
    ticketPrice: 1000,
    ticketQuantity: 100,
  },
  {
    eventName: "Prithvi Theatre Festival",
    image: "https://picsum.photos/id/10/1920/1080",
    date: "2024-04-12",
    time: "18:00",
    venue: "Prithvi Theatre",
    location: "Mumbai, MH",
    section: "Main Hall",
    seat: "F15",
    ticketHolder: "Available",
    bookingRef: "BMS-PT-008",
    eventType: "Theatre",
    ageRating: "all",
    reviews: 4.6,
    ticketPrice: 1000,
    ticketQuantity: 100,
  },
];

export default function EventsRow() {
  return (
    <Carousel
      title="Events"
      titleClassName="text-[#F8D48D]"
      itemClassName="gap-3 [&>*]:cursor-pointer"
    >
      {events.map((event) => (
        <Link href={`/events/${event.bookingRef}`}>
          <EventCard key={event.eventName} {...event} />
        </Link>
      ))}
    </Carousel>
  );
}
